Only flash led in PCIeSoC.
clk125 domain doesn't exist in BaseSoC.

ERROR: [Synth 8-1031] clk125_clk is not declared [lite/netv2-soc/build/gateware/top.v:7993]